In [ ]:
!pip install pycaret --user

In [1]:
from pycaret.classification import *
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("prototype_9.csv", encoding='cp949')
data

,CLEAR,cavity,사출속도,사출압력,사출위치,사출시간,보압속도,보압압력,보압시간,계량속도,계량위치,계량위치(석백),계량시간,금형온도(상부),금형온도(하부),냉각,쿠션,실린더온도.노즐,실린더온도.H1,실린더온도.H2,실린더온도.H3,실린더온도.H4,불량유무,Labels
0,0,8,30.0,50,20.0,1.5,25.000000,70.0,0.0,55.0,5.0,5.0,20.000000,50,50,15,11.00,250.0,245,245,240,230.0,1,0
1,0,2,30.0,65,35.0,1.0,25.000000,70.0,1.0,55.0,10.0,5.0,20.000000,50,50,15,18.60,250.0,245,245,240,230.0,1,0
2,0,2,25.0,40,17.0,1.5,10.000000,35.0,1.0,55.0,5.0,5.0,20.000000,50,50,12,9.00,240.0,240,235,230,230.0,1,0
3,0,4,10.0,140,23.0,2.0,22.170704,120.0,3.0,120.0,25.0,3.0,60.000000,60,60,10,11.61,245.0,255,250,245,240.0,1,7
4,0,2,10.0,140,23.0,5.0,21.877409,150.0,3.0,120.0,25.0,3.0,37.712937,55,55,10,13.60,245.0,255,250,245,240.0,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,0,1,30.0,65,32.0,1.0,15.000000,35.0,0.5,40.0,15.0,5.0,33.176879,95,95,15,4.50,275.0,265,260,260,255.0,0,2
950,0,1,25.0,75,35.0,1.1,10.000000,20.0,1.0,70.0,5.0,5.0,33.176879,85,85,12,7.80,315.0,300,295,285,260.0,0,2
951,0,1,30.0,40,35.0,1.5,10.000000,30.0,2.0,70.0,5.0,5.0,27.136288,85,85,12,6.80,290.0,290,290,270,260.0,0,2
952,0,1,13.0,70,25.0,2.2,10.000000,25.0,0.5,80.0,1.0,5.0,33.176879,100,100,10,5.80,290.0,295,290,280,260.0,0,2
953,0,1,15.0,30,32.0,2.0,10.000000,25.0,1.0,90.0,1.0,5.0,28.315236,85,85,15,0.00,275.0,280,275,270,260.0,0,2

In [3]:
train, test= train_test_split(data, test_size=0.2, random_state=224)

In [4]:
print(train.shape)
print(test.shape)

(763, 24)
(191, 24)

In [5]:
clf = setup(data = train, target = '불량유무',
           use_gpu=True, 
            fold=5)
#             categorical_features=[])

In [6]:
best_3 = compare_models(sort = 'AUC', n_select = 3)

In [7]:
blended = blend_models(estimator_list = best_3, fold = 5, method = 'soft')

In [8]:
pred_holdout = predict_model(blended)

In [9]:
final_model = finalize_model(blended)

In [10]:
predictions = predict_model(final_model, data = test)

In [11]:
predictions['Score'].mean()

0.8223251308900527